apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: node:14
      workingDir: $(workspaces.source.path)
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:14
      workingDir: $(workspaces.source.path)
      script: |
        npx jasmine
